version: "3.9"
services:
  db:
    container_name: musicology_db
    image: mysql:8
    env_file: .env
    command:
      - --sql_mode=
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: '/usr/bin/mysql --user=${DATABASE_USER} --password=${DATABASE_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 30s
      retries: 15
  
  backend:
    container_name: musicology_api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_REPO_NAME}:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000