version: "3.9"
services:
  mysql_db:
    container_name: musicology_db
    image: mysql:8
    # env_file: .env
    restart: unless-stopped
    # command: 
    #   - --default-authentication-plugin=mysql_native_password
    #   - --sql_mode=
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 30s
      retries: 15
  backend:
    container_name: musicology_api
    # image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_BREPO_NAME}:latest
    image: repository/backend
    env_file: .env
    restart: unless-stopped
    ports:
      - 8000
    depends_on:
      - mysql_db
    build:
      dockerfile: Dockerfile.BACKEND
  frontend:
    container_name: musicology_pro
    # image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_FREPO_NAME}:latest
    image: repository/frontend
