version: "3.9"
services:
  mysql:
    container_name: musicology_db
    image: mysql:8
    # env_file: .env
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: '/usr/bin/mysql --user=${DATABASE_USER} --password=${DATABASE_PASSWORD} --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 30s
      retries: 15
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  backend:
    container_name: musicology_api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_BREPO_NAME}:latest
    env_file: .env
    restart: always
    ports:
      - 8000
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.BACKEND
  frontend:
    container_name: musicology_pro
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-central-1.amazonaws.com/${ECR_FREPO_NAME}:latest
    env_file: .env
    restart: always
    ports:
      - 3000
    depends_on:
      - db
      - backend
    build:
      dockerfile: Dockerfile.FRONTEND
    