FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install app dependencies
RUN npm install && npm install -g knex && npm run build
# RUN npm run migrate
# RUN npm run seed

# If you are building your code for production
# RUN npm ci --omit=dev

# EXPOSE 8000
CMD [ "npm", "start" ]
