version: "3.9"
services:
  db:
    container_name: musicology_db
    command:
      - --sql_mode=
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=musicology
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 30s
      retries: 15
