FROM node:18

# Create app directory
WORKDIR /usr/src/app

RUN git clone https://github.com/bikboktech/musicology.pro

WORKDIR /usr/src/app/musicology.pro
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
# Bundle app source
COPY . .

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

EXPOSE 3000
CMD [ "npm", "start" ]
