name: Changelog

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  changelog:
    name: changelog
    runs-on: ubuntu-latest
    environment: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Conventional Changelog Action
        id: conventional_changelog_action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          tag-prefix: 'v'
          version-file: package.json
          
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.conventional_changelog_action.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.conventional_changelog_action.outputs.tag }}
          release_name: ${{ steps.conventional_changelog_action.outputs.tag }}
          body: ${{ steps.conventional_changelog_action.outputs.clean_changelog }}

  godaddy-deployment:
    name: godaddy-deployment
    runs-on: self-hosted
    needs: changelog
    if: ${{ github.event.pull_request.base.ref == 'main' }}
    environment: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Pull & Run
        run: |
          cd /home/bikboktech/public/musicology-api.pro/
          git checkout main
          git pull origin main

          screen -XS musicology-api.pro quit || true
          echo "::notice::Closed active musicology-api.pro sessions"
          RUNNER_TRACKING_ID="" && ./yourtool screen -dmS musicology-api.pro bash -c "npm run start"
          screen -ls
          echo "::notice::Opened a new musicology-api.pro session"
      